spring.application.name=project_management_class
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=project_management_class

server.port=8080
logging.level.com.example.project_management_class=DEBUG
